version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: phpunit/phpunit
        update-types: ["version-update:semver-patch"]
      - dependency-name: phpstan/phpstan
        update-types: ["version-update:semver-patch"]
