build:
  environment:
    php: 8.0.0

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      environment:
        php:
          ini:
            "xdebug.mode": coverage
      tests:
        override:
          - phpcs-run ./src
          - command: "vendor/bin/phpunit test/phpunit --coverage-clover test/phpunit/_coverage --whitelist src"
            coverage:
              file: "test/phpunit/_coverage"
              format: "php-clover"

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - test/*
    - vendor/*